package drivers

import (
	_ "codeberg.org/alist/alist/v3/drivers/115"
	_ "codeberg.org/alist/alist/v3/drivers/115_open"
	_ "codeberg.org/alist/alist/v3/drivers/115_share"
	_ "codeberg.org/alist/alist/v3/drivers/123"
	_ "codeberg.org/alist/alist/v3/drivers/123_link"
	_ "codeberg.org/alist/alist/v3/drivers/123_share"
	_ "codeberg.org/alist/alist/v3/drivers/139"
	_ "codeberg.org/alist/alist/v3/drivers/189"
	_ "codeberg.org/alist/alist/v3/drivers/189pc"
	_ "codeberg.org/alist/alist/v3/drivers/alias"
	_ "codeberg.org/alist/alist/v3/drivers/alist_v2"
	_ "codeberg.org/alist/alist/v3/drivers/alist_v3"
	_ "codeberg.org/alist/alist/v3/drivers/aliyundrive"
	_ "codeberg.org/alist/alist/v3/drivers/aliyundrive_open"
	_ "codeberg.org/alist/alist/v3/drivers/aliyundrive_share"
	_ "codeberg.org/alist/alist/v3/drivers/azure_blob"
	_ "codeberg.org/alist/alist/v3/drivers/baidu_netdisk"
	_ "codeberg.org/alist/alist/v3/drivers/baidu_photo"
	_ "codeberg.org/alist/alist/v3/drivers/baidu_share"
	_ "codeberg.org/alist/alist/v3/drivers/chaoxing"
	_ "codeberg.org/alist/alist/v3/drivers/cloudreve"
	_ "codeberg.org/alist/alist/v3/drivers/cloudreve_v4"
	_ "codeberg.org/alist/alist/v3/drivers/crypt"
	_ "codeberg.org/alist/alist/v3/drivers/doubao"
	_ "codeberg.org/alist/alist/v3/drivers/doubao_share"
	_ "codeberg.org/alist/alist/v3/drivers/dropbox"
	_ "codeberg.org/alist/alist/v3/drivers/febbox"
	_ "codeberg.org/alist/alist/v3/drivers/ftp"
	_ "codeberg.org/alist/alist/v3/drivers/github"
	_ "codeberg.org/alist/alist/v3/drivers/github_releases"
	_ "codeberg.org/alist/alist/v3/drivers/google_drive"
	_ "codeberg.org/alist/alist/v3/drivers/google_photo"
	_ "codeberg.org/alist/alist/v3/drivers/halalcloud"
	_ "codeberg.org/alist/alist/v3/drivers/ilanzou"
	_ "codeberg.org/alist/alist/v3/drivers/ipfs_api"
	_ "codeberg.org/alist/alist/v3/drivers/kodbox"
	_ "codeberg.org/alist/alist/v3/drivers/lanzou"
	_ "codeberg.org/alist/alist/v3/drivers/lenovonas_share"
	_ "codeberg.org/alist/alist/v3/drivers/local"
	_ "codeberg.org/alist/alist/v3/drivers/mediatrack"
	_ "codeberg.org/alist/alist/v3/drivers/mega"
	_ "codeberg.org/alist/alist/v3/drivers/misskey"
	_ "codeberg.org/alist/alist/v3/drivers/mopan"
	_ "codeberg.org/alist/alist/v3/drivers/netease_music"
	_ "codeberg.org/alist/alist/v3/drivers/onedrive"
	_ "codeberg.org/alist/alist/v3/drivers/onedrive_app"
	_ "codeberg.org/alist/alist/v3/drivers/onedrive_sharelink"
	_ "codeberg.org/alist/alist/v3/drivers/pikpak"
	_ "codeberg.org/alist/alist/v3/drivers/pikpak_share"
	_ "codeberg.org/alist/alist/v3/drivers/quark_uc"
	_ "codeberg.org/alist/alist/v3/drivers/quark_uc_tv"
	_ "codeberg.org/alist/alist/v3/drivers/quqi"
	_ "codeberg.org/alist/alist/v3/drivers/s3"
	_ "codeberg.org/alist/alist/v3/drivers/seafile"
	_ "codeberg.org/alist/alist/v3/drivers/sftp"
	_ "codeberg.org/alist/alist/v3/drivers/smb"
	_ "codeberg.org/alist/alist/v3/drivers/teambition"
	_ "codeberg.org/alist/alist/v3/drivers/terabox"
	_ "codeberg.org/alist/alist/v3/drivers/thunder"
	_ "codeberg.org/alist/alist/v3/drivers/thunder_browser"
	_ "codeberg.org/alist/alist/v3/drivers/thunderx"
	_ "codeberg.org/alist/alist/v3/drivers/trainbit"
	_ "codeberg.org/alist/alist/v3/drivers/url_tree"
	_ "codeberg.org/alist/alist/v3/drivers/uss"
	_ "codeberg.org/alist/alist/v3/drivers/virtual"
	_ "codeberg.org/alist/alist/v3/drivers/vtencent"
	_ "codeberg.org/alist/alist/v3/drivers/webdav"
	_ "codeberg.org/alist/alist/v3/drivers/weiyun"
	_ "codeberg.org/alist/alist/v3/drivers/wopan"
	_ "codeberg.org/alist/alist/v3/drivers/yandex_disk"
)

// All do nothing,just for import
// same as _ import
func All() {

}
